### ISSUE TITLE
Readmes/Wiki

### ISSUE THREAD

**Issue by ginafish** [cascadeth/OSU-IT-Tool-Mods#9]
Issue tracker for discussion of initial documentation standards/requirements.

From: https://github.com/cascadeth/OSU-IT-Tool-Mods/pull/8
"Anyone and everyone that has a style to submit or currently has one must create a wiki page for it that contains info about the style, as well as preview images.
Readme can have the gist of the repo, and then point to the wiki for specifics on installations of various types, as well as info on the styles contained in the repo"
"O and maybe a contact readme in each person's named directories"

**Comment by ginafish** [comment]
Okay thoughts...
So a few ways we can organize.

## Readmes in each directory

Readmes can have...

- Dev contact info
- Style summary (ie: this style makes things look dark with white text and have sound effects)
- Installation guide


## Wiki

Wiki can have...

- List of styles and scripts
- Style summaries
- Installation guide(s)
- Dev contact info (and maybe something about whether or not they are an active employee so that people who no longer work for us don't get pinged for update requests)


Not sure how and where we'd like to have things.  I'd like to avoid having too much redundancy (ie: people being able to link to a wiki page for installation instructions in their readme, or having a "install this way unless readme says otherwise" process, with a preference for the latter).

Honestly, I almost feel like we should have everything in the wiki instead of having to maintain Readmes in every single directory.

**Comment by ginafish** [comment]
Oh, and should we have some sort of issue opening process for updating styles/scripts?

**Comment by ginafish** [comment]
Should we refer to people who have submitted code as "submitters" (yes Chrome spellcheck it is a real word... not sure why it thinks "submitter" is but "submitters" isn't) or "devs" in our documentation?

**Comment by cascadeth** [comment]
### Readmes in each directory: 
Seems like a good idea.  I would think though that since there's only 3 ways to install the files, the wiki should have an installation section to explain the "how to"s by detail.  Obviously more detail than the following, but the gist:

- By specific CSS = copy and paste into "Write your own style"
- By MOZILLA AIO = Import option under "Write your own style"
- By package = Retrieve Backup from main menu in Stylish manager

So the readme could say:  
`Refer to this(insert link) section of the wiki for general installation instructions.  For this specific section of the style, do this list of stuff`  E.g. your TD field manipulations for tickets.  

### Wiki Organization Suggestion
- First Page: Wiki Summary and Table of Contents(with links to individual pages)
- Second Page: List of Styles and Scripts (probably listed by site, and with author attributes, especially if developed by someone not us{userstyle.org pulled in})
- Third Page: Installation instructions
   - A section per installation style type(per style, per AIO, per package)
   - A section for user scripts installation
- Fourth Page: Dev Contact Info

### Updating Scripts/Requests
I would think we can create issues in Github like this one.  It allows for code reference, a log of communication and "trackability", allows issues to be assigned to either the developer or another, etc 

### Naming Scheme
I would think two titles would be in effect: _Author_ and _Designer_.  It provides the best idea of who done what.  The author may not necessarily be the _designer_.  Author implies that this is the person who individually wrote the code - typed it out line by line.  Let's say <H3-wh0-is-n0t-Jad3> says to me:  "I want Cyder to look like this: Blah, blahbittyblah, blaaahhhhhh", but they have no idea how to code that.  They are the original designer, while I would be the author to write the code.  The wiki would specifically have to mention this, but it'd be easy to track.

**Comment by ginafish** [comment]
### Readmes

Yeah we could have a generic Readme for people to use that would involve something like...  

> Dev: blah  
> Repository link: this  
>  
> Refer to wiki for dev contact information \(because updating every single readme would be silly).  Please do/don't contact me for requests, and submit any requests in as Issues on the repository page.  
>  
>\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#  
>  
>Explanation of style:  
>Blurb.  
>  
>\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#  
>  

And then either:  

Generic installation process:  
> This is a [type] installation.  For instructions, follow the [type] installation guide in the wiki.  
  
Specific Installation Process:  
> Follow [type] installation instructions from the wiki up until blah, or don't and just follow the instructions below, and then do:  
> 1. blah.  
> 2. ???  
> 3. Profit.  
  
### Wiki Organization

Take a look at what I have so far.  Basically have that, only with an additional "Demo" page for people adding a page for individual styles.  Thoughts from when I made it were basically "Have list of themes, and then if people want more information they can refer to a specific wiki page for that theme," but I'm not sure how keen I am on that now; might be better to have that information in the theme list so that people can just scroll through and compare easier?

### Updating Scripts/Requests

Agreed!

### Naming

Aight, I'll go with "Author" then lol.  I'm not sure how relevant "designer" is; I'd go with "requester" if necessary.

**Comment by ginafish** [comment]
Note to self, need to update documented processes to account for people who want to request changes who don't want to create Github accounts.

**Comment by ginafish** [comment]
Note to self, contact policy should be on contact wiki page, not in readmes.

**Comment by cascadeth** [comment]
Closing this and opening individual issues for specific Wiki updates.
